name: Deploy playground

on:
  workflow_dispatch:
  push:
    branches: [develop]

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: |
          mkdir packages
          cd packages
          git clone --depth=1 https://github.com/Gandi-IDE/scratch-storage
          cd scratch-storage
          npx json -f package.json -I -e "this.name='scratch-storage'"
          npm install
          npm run build > /dev/null
          echo "build end"
          npm link
          cd ..
          git clone --depth=1 https://github.com/Gandi-IDE/scratch-parser
          cd scratch-parser
          npx json -f package.json -I -e "this.dependencies.ajv='^6.3.0'"
          rm package-lock.json
          npm install
          npm link
          echo "linked"
          cd ../..
          npx json -f package.json -I -e "this.dependencies['@babel/runtime']='^7.29.2';this.devDependencies['scratch-render-fonts']='^1.0.0-prerelease.20231017225105';delete this.dependencies['scratch-parser'];delete this.devDependencies['scratch-storage']"
          cat package.json
          rm yarn.lock
          ls
          npm install --verbose
          echo "third-party module installed"
          npm link scratch-storage scratch-parser
          ls ./packages
          echo "packages/*" >> .eslintignore
      - name: Build playground
        run: npm run build
      - name: Build docs
        run: npm run docs
        # We expect to see syntax errors from the old jsdoc cli not understanding some of our syntax
        # It will still generate what it can, so it's safe to ignore the error
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./playground/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
